### ISSUE TITLE
Vehicle identifiers Doku falsch

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#101]
Das müsste eine Liste sein:

ich bin nach Doku vorgegangen https://docs.evcc.io/docs/guides/vehicles
```
vehicles:
  - name: zoe
    ...
    identifier: "<kopierte Wert>"
```

Edit: mit Liste funktioniert es, danke für den Hinweis

_Originally posted by @Waldmensch1 in https://github.com/evcc-io/evcc/issues/3151#issuecomment-1098189720_
