### ISSUE TITLE
template for Fronius Symo inverters

### ISSUE THREAD

**Issue by Macrisu** [evcc-io/docs#124]
**Fronius Symo 1/3 phase** + smart meter are very popular, but a template is missing from the docs.

This is my working template for 3 phase inverters, please add it to docs.

It's working on 
- Fronius Symo 8.2-3 with 63A-3 Smartmeter (old smartmeter, the new one it's TS 65A-3)
- Fronius Symo 20-3 with TS 5kA Smartmeter

```
meters:  
- name: grid
  type: modbus
  model: sunspec
  uri: 192.168.1.xxx:502 #inverter fix IP
  id: 240
  power: 213:W # sunspec model 213 meter

- name: pv
  type: modbus
  model: sunspec
  uri: 192.168.1.xxx:502 #inverter fix IP (same ip as grid meter)
  id: 1
```

Modbus data export must be activated on the inverter (service menu) as in this image:
https://user-images.githubusercontent.com/16325429/160246056-d8a0f13a-2a2f-4cd0-a599-8bdee74674a7.jpg
