### ISSUE TITLE
Konsistente Einrückung

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#16]
Bisher hatten wir

```yaml
foo:
- bar
```

Als Einrückung durchgängig verfolgt. Unter [Go-](https://docs.evcc.io/docs/devices/chargers#go-echarger-homeprov3) sehe ich 

```yaml
chargers:
  - name: my_charger
    type: go-e
    token: 4711c # go-e cloud API token
    cache: 10s # go-e cloud API cache duration
```

Beides ist richtig, Konsistenz wäre dennoch schön.

**Update**

Genau genommen ist es überall anders soweit ich sehe. Gibts dafür einen guten Grund? Unterschiede ignorieren oder auch README und dist umbauen?
