### ISSUE TITLE
sign()-Funktion dokumentieren

### ISSUE THREAD

**Issue by premultiply** [evcc-io/docs#226]
Ref https://github.com/evcc-io/evcc/pull/4494

**Comment by VolkerK62** [comment]
nachdem ich die mathematische Signum-Funktion jetzt (hoffentlich) verstanden habe ...
(Jede positive Zahl wird zu +1, jede negative zu -1 und 0 bleibt 0)

das ist doch für das calc-plugin, oder?
für welche use cases bräuchte man das?

**Comment by andig** [comment]
Wenn Du einen vorzeichenbehafteten Wert hast (Phasenleistung) aus dem Du einem Absolutwert ein Vorzeichen verpassen willst (Phasenstrom) machst Du eine Multiplikation mit dem Vorzeichen des anderen Wertes.

**Comment by VolkerK62** [comment]
Ah, um z.B. aus dem Shelly 3EM die korrekten Phasenströme zu bekommen (Lastmanagement).

Und wie sähe die Syntax aus?

```
source: calc
mul:
- sign:
    source: http
      uri: http://192.168.178.27/cm?cmnd=Status%208
      jq: .StatusSNS.SML.Power
- source: http
    uri: http://192.168.178.27/cm?cmnd=Status%208
    jq: .StatusSNS.SML.Current

```

**Comment by andig** [comment]
Mul braucht mehrere Sources- die erste ist dann halt wieder ein calc.

**Comment by VolkerK62** [comment]
ich habe mal hier beim SDM630 gespickelt ;-)  https://github.com/evcc-io/evcc/pull/5131

Dann schau ich mal, wie ich das in der Doku unterbringe.

```
source: calc
mul:
- source: calc
  sign:
    source: http
      uri: http://192.168.178.27/cm?cmnd=Status%208
      jq: .StatusSNS.SML.Power
- source: http
    uri: http://192.168.178.27/cm?cmnd=Status%208
    jq: .StatusSNS.SML.Current
```
