### ISSUE TITLE
ntfy message not transmitted if priority is set to "normal"

### ISSUE THREAD

**Issue by stephandiehl** [evcc-io/docs#258]
### Describe the bug

In the examples, priority is set to `normal`, which does not work. It should be `default`.
e.g. https://docs.evcc.io/docs/reference/configuration/messaging/

### Steps to reproduce

1.
2.
3.
...

### Configuration details

```yaml
# push messages
messaging:
  events:
    start: # charge start event
      title: Charge started
      msg: Started charging in "${mode}" mode
    stop: # charge stop event
      title: Charge finished
      msg: Finished charging ${chargedEnergy:%.1fk}kWh in ${chargeDuration}.
    connect: # vehicle connect event
      title: Car connected
      msg: "Car connected at ${pvPower:%.1fk}kW PV"
    disconnect: # vehicle connected event
      title: Car disconnected
      msg: Car disconnected after ${connectedDuration}
    soc: # vehicle soc update event
      title: SoC updated
      msg: Battery charged to ${vehicleSoC:%.0f}%
    guest: # vehicle could not be identified
      title: Unknown vehicle
      msg: Unknown vehicle, guest connected?
  services:  
    - type: ntfy
      uri: https://ntfy.sh/planet-diehl-alerts
      priority: normal
```

### Log details

```text
no log
```

### What type of operating system are you running?

Linux

### Version

evcc version 0.110.1
