### ISSUE TITLE
pushover: add devices

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#280]
https://github.com/evcc-io/evcc/pull/5948#issue-1562813820
https://github.com/evcc-io/evcc/issues/5944#issue-1562185053

**Comment by VolkerK62** [comment]
Messaging nutze ich nicht. Dehalb brauch ich mal ne Erklärung.
```
- type: pushover
  app: # API Token/Key der in Pushover angelegten Aplication
  recipients:
  - # Liste der Empfänger: entweder User Key or Delivery Group. In Pushover angelegte Gruppen können auf bestimmte Geräte eingeschränkt werden.
```
Wo ist denn der Unterschied zwischen `recipients` und `devices` ? Beides sind doch Empfänger.
