### ISSUE TITLE
Ergänzung FAQ "Wintermodus"

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#295]
Michael Geers via Slack:

Meine aktuelle Lösung für das von dir beschriebene Szenario sieht so aus:
```
    enable:
      delay: 1m 
      threshold: -200
    disable:
      delay: 30m 
      threshold: 1200
```
Dadurch startet die Ladung im PV Modus sobald eine Minute lang 200W eingespeist werden und endet wenn für eine halbe Stunde lang mehr als 1200W aus dem Netz gezogen wird. Letzteres ist meine Mindestladeleisung (1,4kW - 200W).
Ohne `residualpower`.
