### ISSUE TITLE
2 MQTT Broker in evcc

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#380]
Eigentlich... ja. Aber: ist im Teslamate Template nicht ausgeprägt. 

Was kannst du machen: Teslamate konfigurieren und das Ergebnis anschauen:

    evcc configure --category vehicle --expand

Ergibt:

```yaml
  name: ev1
  type: custom
  icon: car
  soc:
    source: mqtt
    topic: teslamate/cars/1/battery_level
    timeout: 720h # 30d
  status:
    source: combined
    plugged:
      source: mqtt
      topic: teslamate/cars/1/plugged_in
      timeout: 720h # 30d
    charging:
      source: mqtt
      topic: teslamate/cars/1/charger_actual_current
      timeout: 720h # 30d
  range:
    source: mqtt
    topic: teslamate/cars/1/rated_battery_range_km
    timeout: 720h # 30d
```

Jetzt kannst Du unter jedem `source: mqtt` die weitere Mqtt Config, v.a. `broker` ergänzen. Und das Ganze dann unter `vehicles` als Fahrzeug übernehmen.

Ach ja: und natürlich solltest Du auch ioBroker oder Teslamate auf einen anderen Broker umbiegen können um nur einen verwenden zu müssen!

PS.: Grüße in den Kyffhäuser :)

_Originally posted by @andig in https://github.com/evcc-io/evcc/discussions/7899#discussioncomment-5861971_
