### ISSUE TITLE
Doku: add dedicated co2 tariff

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#390]
@andig siehst du hier noch ein Todo? Ich find das sieht gut aus.

@VolkerK62 Magst du die tariff Doku anpassen wenn das released ist? Neue Struktur:
```
tariff:
  grid: ...
  feedin: ...
  co2: ... (neu)
  planner: ... (advanced, manual control)
```

Der `planner` wird jetzt automatisch ermittelt: Dynamische Grid-Tarife habe Vorrang, gibts keinen wird der CO2 Tarif genommen, sonst ggf. der statische Grid-Tarif. Ein manuell gesetzter `planner` überschreibt diese Logik. Dies sollte aber nur in Ausnahmefällen erforderlich sein.

_Originally posted by @naltatis in https://github.com/evcc-io/evcc/issues/8089#issuecomment-1568886687_
