### ISSUE TITLE
Add Huawei dongle

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#41]
Needs connect delay and delay:

    meters:
    - name: grid # Huawei grid power import export (when smart power sensor is present)
      type: custom
      power:
        source: modbus
        timeout: 10s
        connectdelay: 5s
        delay: 2s
        model: huawei
        uri: <ip>:502
        id: 2
        register:
          address: 37113 # Grid import export power
          type: holding
          decode: int32
        scale: -1
      energy:
        source: modbus
        timeout: 10s
        connectdelay: 5s
        delay: 2s
        model: huawei
        uri: <ip>:502
        id: 2
        register:
          address: 37121 # Grid active energy
          type: holding
          decode: int32
        scale: 0.01
      currents:
      - source: modbus
        model: huawei
        uri: <ip>:502 # inverter port
        id: 2
        register:
          address: 37107 # Huawei phase A grid current
          type: holding
          decode: int32
        scale: -0.01
      - source: modbus
        model: huawei
        uri: <ip>:502 # inverter port
        id: 2
        register:
          address: 37109 # Huawei phase B grid current
          type: holding
          decode: int32
        scale: -0.01
      - source: modbus
        model: huawei
        uri: <ip>:502 # inverter port
        id: 2
        register:
          address: 37111 # Huawei phase C grid current
          type: holding
          decode: int32
        scale: -0.01
    - name: battery
      type: custom
      power:
        source: modbus
        timeout: 10s
        connectdelay: 5s
        delay: 2s
        model: huawei
        uri: <ip>:502
        id: 2
        register:
          address: 37001
          type: holding
          decode: int32
      soc:
        source: modbus
        timeout: 10s
        connectdelay: 5s
        delay: 2s
        model: huawei
        uri: <ip>:502
        id: 2
        register:
          address: 37004
          type: holding
          decode: uint16
        scale: 0.1

**Comment by DerAndereAndi** [comment]
> Huawei grid power import export (when smart power sensor is present)

Das können wir nicht erkennen? Dann müssten das wohl ein extra Template werden

**Comment by RTTTC** [comment]
> 

Smart power sensor is in essence a smart power meter, that has to be orderred and installed separately, so user would know if it is present or not.

**Comment by RTTTC** [comment]
I was tuning my config all night, and with this config EVCC runs fairly fast and no errors.
I am not using `Energy` meter at the moment, as I think its not needed for me, also please see here - Im not sure if thats the right register for it https://github.com/evcc-io/evcc/discussions/1928#discussioncomment-1976158
If `currents` is not utilised by evcc at the moment, probably good idea to not use it also, to speed everything up - perhaps advice users about it in template ?

Huawei grid and pv meters via Huawei Sdongle Modbus TCP connection:
```
meters:

- name: grid # Huawei grid import export power
  type: custom
  power:
    source: modbus
    timeout: 10s
    connectdelay: 1s
    model: huawei
    uri: <ip>:502
    rtu: false
    id: 1
    register:
      address: 37113 # Huawei import/export active power / IF Huawei smart power sensor is installed
      type: holding
      decode: int32
    scale: -1

#  energy:
#    source: modbus
#    delay: 1s
#    model: huawei
#    uri: <ip>:502
#    rtu: false
#    id: 1
#    register:
#      address: 37119 #  Grid active energy ???
#      type: holding
#      decode: int32
#    scale: 0.01

  currents:
    - source: modbus # Huawei phase A grid current
      timeout: 10s
      model: huawei
      uri: <ip>:502
      rtu: false
      id: 1
      register:
        address: 37107 # Huawei phase A grid current / IF Huawei smart power sensor is installed
        type: holding
        decode: int32
      scale: -0.01

    - source: modbus # Huawei phase B grid current
      timeout: 10s
      model: huawei
      uri: <ip>:502
      rtu: false
      id: 1
      register:
        address: 37109 # Huawei phase B grid current / IF Huawei smart power sensor is installed
        type: holding
        decode: int32
      scale: -0.01

    - source: modbus # Huawei phase C grid current
      timeout: 10s
      model: huawei
      uri: <ip>:502
      rtu: false
      id: 1
      register:
        address: 37111 # Huawei phase C grid current / IF Huawei smart power sensor is installed
        type: holding
        decode: int32
      scale: -0.01

- name: pv1 # Huawei Solar generation power
  type: custom
  power:
    source: modbus
    timeout: 10s
    connectdelay: 1s
    model: huawei
    uri: <ip>:502
    rtu: false
    id: 1
    register:
      address: 32080 # Active generation power
      type: holding
      decode: int32

```
