### ISSUE TITLE
SMA Hybrid-WR, max. AC-Leistung wird nicht berücksichtigt

### ISSUE THREAD

**Issue by buennerbernd** [evcc-io/docs#574]
Ich habe einen SMA STP 10.0, Panels mit 13 kW Peak und BYD HVS 7.7 kWh.

Config:

```
interval: 20s

site:
...
  residualPower: 100
  maxGridSupplyWhileBatteryCharging: 50

vehicles:
...
  features: ["coarsecurrent"]
```

Wenn die PV-Leistung über 10kW ist und die Hausbatterie noch nicht voll ist, dann habe ich die meiste Zeit etwa 300W Netzbezug.
Ich denke, es liegt daran, dass evcc keine Ahnung hat, was die maximale AC-Leistung des Wechselrichters ist und diese nicht mit in die Steuerung einfließt.
Ich vermute, evcc tastet sich mit Hilfe des Parameters maxGridSupplyWhileBatteryCharging an diese Grenze heran, liegt aber Prinzip-bedingt meistens drüber.
Mein Vorschlag ist:

1. Die maximale AC-Leistung des WR vom Modell ableiten oder konfigurierbar zu machen.
2. Die Steuerung in evcc so anzupassen, dass die aktuelle AC-Leistung nicht die maximale AC-Leistung übertrifft.

Generell würde ich die Möglichkeit begrüßen, eine maximale AC-Leistung des WR angeben zu können. Durch ungünstiges Timing der Messwerte der ganzen Zähler kommen nicht selten Werte zustande, die mehr verfügbare Leistung suggerieren. Dann schießt evcc mit der Ladeleistung über das Ziel hinaus.

Viele Grüße, Stefan.
