### ISSUE TITLE
Bug in der Dokumentation der CO2 Tarife

### ISSUE THREAD

**Issue by mpw96** [evcc-io/docs#672]
### Describe the bug

Unter "Geräte" soll man bspw. Grünstromindex so konfigurieren:
```yaml
tariffs:
  co2:
    type: template
    template: grünstromindex
    zip: 12345
```

Aber in der Referenz Doku für die evcc.yaml so:
```yaml
tariffs:
  co2:
    type: grünstromindex
    zip: 12345
```

Es scheint beides zu funktionieren, aber es ist mindestens verwirrend. Bitte vereinheitlicht die Dokumentation.

### Steps to reproduce

Not applicable.

### Configuration details

```yaml
Siehe Beschreibung.
```

### Log details

```text
Not applicable.
```

### What type of operating system are you running?

Docker container

### Nightly build

- [X] I have verified that the issue is reproducible with the latest nightly build
