### ISSUE TITLE
Klatstellung Syntax-Beispiel

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#764]
Gotcha! I was confused by the docs specifically what is shared below. My bug was suggesting perhaps mentioning that Open-Meteo doesn't support site.

https://docs.evcc.io/en/docs/tariffs#pv-forecast

It is possible to combine multiple solar forecasts to cover multiple solar arrays. The values will be summed up for this purpose. Use the following syntax:

```
tariffs:
  solar:
    - type: template
      template: solcast
      site: aaa # solar array A
      token: xxxxx
      interval: 6h # increased interval to not exceed solcast's 10req/day limit
    - type: template
      template: solcast
      site: bbb # solar array B
      token: xxxxx
      interval: 6h # increased interval to not exceed solcast's 10req/day limit

```

_Originally posted by @danielraffel in https://github.com/evcc-io/evcc/discussions/19633#discussioncomment-12445057_
