### ISSUE TITLE
Documentation: SG-Ready example needs calc offset of 2

### ISSUE THREAD

**Issue by mbfoo** [evcc-io/docs#792]
### Describe the bug

I am using the SG-Ready setup described here: https://docs.evcc.io/docs/devices/heating
After upgrading to 0.203.5, I got errors that the headpump is in dimm state.
I guess this is caused by evcc-io/evcc#20747.

It seems to be fixed by changing the getmode calc add value from 1 to 2 in the yaml.

### Steps to reproduce

1. Use SG-Ready setup from https://docs.evcc.io/docs/devices/heating
2. Upgrade to 0.203.5

### Configuration details

```yaml
- name: waermepumpe-charger
  type: sgready
  setmode:
    source: switch
    switch:
      - case: 1 # normal
        set:
          source: const
          value: false
          set:
            source: charger
            config:
              type: template
              template: shelly
              host: sly-ug-wp-pv
      - case: 2 # boost
        set:
          source: const
          value: true
          set:
            source: charger
            config:
              type: template
              template: shelly
              host: sly-ug-wp-pv
      - case: 3 # dimm (not supported)
        set:
          source: error
          error: ErrNotAvailable
  getmode:
    source: calc
    add:
      - source: const
        value: 1
      - source: charger
        config:
          type: template
          template: shelly
          host: sly-ug-wp-pv
  temp:
    source: mqtt
    topic: iobroker-js/hot-water-temperature
```

### Log details

```text
[lp-3 ] ERROR 2025/05/13 09:10:05 charger status: dimm mode
```

### What type of operating system or environment does evcc run on?

Linux

### External automation

- [x] I have made sure that no external automation like HomeAssistant or Node-RED is active or accessing any of the mentioned devices when this issue occurs.

### Nightly build

- [x] I have verified that the issue is reproducible with the latest nightly build

### Version

0.203.5
